[book]
authors = ["Ayoub EL Mhamdi"]
title = "Linux docs"
language = "en"

[build]
create-missing = false

[output.html]
site-url = "/linux/"
no-section-label = false
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/ayoubelmhamdi/linux"
edit-url-template = "https://github.com/ayoubelmhamdi/linux/tree/master/{path}"

[preprocessor.katex]
